name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Build Package
      run: dotnet pack -c Release -o /home/runner/work/SQLite/release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source #-p:Version=1.0.0-betaABC
      #--version-suffix "test-${{github.run_number}}"
    
    - name: Prep package
      run: dotnet nuget add source --username RusysDev --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/RusysDev/index.json"

    - name: Push package to GitHub packages     
      run: dotnet nuget push "/home/runner/work/SQLite/release/*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
    
    #  run: dotnet nuget push /home/runner/work/SQLite/release/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source "github"

    #- name: Push symbols to GitHub packages     
    #  run: dotnet nuget push /home/runner/work/SQLite/release/*.snupkg --api-key ${{secrets.GITHUB_TOKEN}} --source "github"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nugetPackage
        path: /home/runner/work/SQLite/release
          
